// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4abJhoDo9pdukiQCsKRM_s736UX_tc-w',
    appId: '1:258339805204:web:65bd5fde5d5f8073d86f01',
    messagingSenderId: '258339805204',
    projectId: 'ask-app-9df84',
    authDomain: 'ask-app-9df84.firebaseapp.com',
    storageBucket: 'ask-app-9df84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8j4P0x5xtQStiOeTmn2iUB13sU5EuI3s',
    appId: '1:258339805204:android:0955e1b6234fe689d86f01',
    messagingSenderId: '258339805204',
    projectId: 'ask-app-9df84',
    storageBucket: 'ask-app-9df84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgycXo6YrfaNM80VrP0xAnRoWa_XEml60',
    appId: '1:258339805204:ios:1c10c0d78e1aeca7d86f01',
    messagingSenderId: '258339805204',
    projectId: 'ask-app-9df84',
    storageBucket: 'ask-app-9df84.appspot.com',
    iosBundleId: 'org.ryan.sparcs.ask.ask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgycXo6YrfaNM80VrP0xAnRoWa_XEml60',
    appId: '1:258339805204:ios:1c10c0d78e1aeca7d86f01',
    messagingSenderId: '258339805204',
    projectId: 'ask-app-9df84',
    storageBucket: 'ask-app-9df84.appspot.com',
    iosBundleId: 'org.ryan.sparcs.ask.ask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4abJhoDo9pdukiQCsKRM_s736UX_tc-w',
    appId: '1:258339805204:web:f18d1f7d6ae4073ad86f01',
    messagingSenderId: '258339805204',
    projectId: 'ask-app-9df84',
    authDomain: 'ask-app-9df84.firebaseapp.com',
    storageBucket: 'ask-app-9df84.appspot.com',
  );

}